/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/drone.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -100, -5]} />
      <group position={[0, 0.12, -12.91]} rotation={[1.32, 0, 0]}>
        <group position={[0, 0, 77.5]}>
          <group position={[0, 0, -37.5]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[19.24, -26.58, -0.75]} rotation={[Math.PI / 2, 1.03, -Math.PI / 2]}>
              <group position={[-0.68, -0.38, 1.96]} rotation={[0, 0, 0]}>
                <group position={[12.89, -9.61, -0.73]} rotation={[-1.24, -1.57, 0]}>
                  <group position={[-2.42, -4.84, -0.01]} rotation={[Math.PI, -1.41, Math.PI]}>
                    <group rotation={[1.28, 0, 0]}>
                      <group position={[0, -22.92, 0.03]}>
                        <group position={[0, 0, 0]} rotation={[1.46, 0, -Math.PI]}>
                          <group position={[0.06, -11.24, 0.08]} rotation={[0, 0, -0.02]}>
                            <group position={[0.14, -9.37, -0.08]}>
                              <group position={[0.01, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
                                <mesh geometry={nodes.L_P7_leg_0.geometry} material={nodes.L_P7_leg_0.material} />
                              </group>
                              <mesh geometry={nodes.L_P6_G_leg_0.geometry} material={nodes.L_P6_G_leg_0.material} />
                            </group>
                            <mesh geometry={nodes.L_P5_M_leg_0.geometry} material={nodes.L_P5_M_leg_0.material} />
                          </group>
                          <mesh geometry={nodes.L_P4_leg_0.geometry} material={nodes.L_P4_leg_0.material} />
                        </group>
                        <mesh geometry={nodes.L_P3_G_leg_0.geometry} material={nodes.L_P3_G_leg_0.material} />
                      </group>
                      <mesh geometry={nodes.L_P2_leg_0.geometry} material={nodes.L_P2_leg_0.material} />
                    </group>
                    <mesh geometry={nodes.L_P1_G_leg_0.geometry} material={nodes.L_P1_G_leg_0.material} />
                  </group>
                  <mesh geometry={nodes.Drone_leg_L_leg_0.geometry} material={nodes.Drone_leg_L_leg_0.material} />
                </group>
                <mesh geometry={nodes.Drone_Panel_L_body_0.geometry} material={nodes.Drone_Panel_L_body_0.material} />
              </group>
              <mesh geometry={nodes.Drone_Gen_L_body_0.geometry} material={nodes.Drone_Gen_L_body_0.material} />
            </group>
            <group position={[-19.24, -26.58, -0.75]} rotation={[Math.PI / 2, -1.03, Math.PI / 2]}>
              <group position={[0.68, -0.38, 1.96]}>
                <group position={[-12.89, -9.61, -0.73]} rotation={[-1.24, 1.57, 0]}>
                  <group position={[2.42, -4.84, -0.01]} rotation={[-Math.PI, 1.31, -Math.PI]}>
                    <group rotation={[1.33, 0, 0]}>
                      <group position={[0, -22.92, 0.03]}>
                        <group position={[0, 0, 0]} rotation={[1.29, 0, Math.PI]}>
                          <group position={[0.01, -11.29, 0.08]} rotation={[0, 0, 0]}>
                            <group position={[-0.01, -9.33, -0.08]}>
                              <group position={[0, 0, 0]} rotation={[1.41, 0, 0]}>
                                <mesh geometry={nodes.R_P7_leg_0.geometry} material={nodes.R_P7_leg_0.material} />
                              </group>
                              <mesh geometry={nodes.R_P6_G_leg_0.geometry} material={nodes.R_P6_G_leg_0.material} />
                            </group>
                            <mesh geometry={nodes.R_P5_M_leg_0.geometry} material={nodes.R_P5_M_leg_0.material} />
                          </group>
                          <mesh geometry={nodes.R_P4_leg_0.geometry} material={nodes.R_P4_leg_0.material} />
                        </group>
                        <mesh geometry={nodes.R_P3_G_leg_0.geometry} material={nodes.R_P3_G_leg_0.material} />
                      </group>
                      <mesh geometry={nodes.R_P2_leg_0.geometry} material={nodes.R_P2_leg_0.material} />
                    </group>
                    <mesh geometry={nodes.R_P1_G_leg_0.geometry} material={nodes.R_P1_G_leg_0.material} />
                  </group>
                  <mesh geometry={nodes.Drone_leg_R_leg_0.geometry} material={nodes.Drone_leg_R_leg_0.material} />
                </group>
                <mesh geometry={nodes.Drone_Panel_R_body_0.geometry} material={nodes.Drone_Panel_R_body_0.material} />
              </group>
              <mesh geometry={nodes['0'].geometry} material={nodes['0'].material} />
            </group>
            <group position={[19.97, 24.56, -6.01]} rotation={[-1.43, 0.37, 1.57]}>
              <group position={[0, -36.16, -10.97]} rotation={[1.87, 0, 0]}>
                <mesh
                  geometry={nodes.Drone_Turb_Blade_L_body_0.geometry}
                  material={nodes.Drone_Turb_Blade_L_body_0.material}
                />
              </group>
              <mesh geometry={nodes.Drone_Turb_M_L_body_0.geometry} material={nodes.Drone_Turb_M_L_body_0.material} />
            </group>
            <group position={[-19.97, 24.56, -6.01]} rotation={[-1.43, -0.37, -Math.PI / 2]}>
              <group name="Drone_Turb_Blade_R" position={[0, -36.16, -10.97]} rotation={[1.87, 0, 0]}>
                <mesh
                  geometry={nodes.Drone_Turb_Blade_R_body_0.geometry}
                  material={nodes.Drone_Turb_Blade_R_body_0.material}
                />
              </group>
              <mesh geometry={nodes.Drone_Turb_M_R_body_0.geometry} material={nodes.Drone_Turb_M_R_body_0.material} />
            </group>
            <group position={[22.44, -9.65, -0.08]} rotation={[Math.PI / 2, 1.3, -Math.PI / 2]}>
              <mesh geometry={nodes.Drone_UPanel_L_body_0.geometry} material={nodes.Drone_UPanel_L_body_0.material} />
            </group>
            <group position={[-22.56, -8.63, 0.14]} rotation={[Math.PI / 2, -1.3, Math.PI / 2]}>
              <mesh geometry={nodes.Drone_UPanel_R_body_0.geometry} material={nodes.Drone_UPanel_R_body_0.material} />
            </group>
            <group position={[0, 33.48, -3.07]}>
              <mesh geometry={nodes.Drone_UPart_body_0.geometry} material={nodes.Drone_UPart_body_0.material} />
            </group>
            <group position={[0, -14.97, 41.51]}>
              <group position={[0, -0.02, -8.91]} rotation={[-3.11, 0, -Math.PI]}>
                <mesh
                  name="1"
                  geometry={nodes['1'].geometry}
                  material={nodes['1'].material}
                  morphTargetDictionary={nodes['1'].morphTargetDictionary}
                  morphTargetInfluences={nodes['1'].morphTargetInfluences}
                />
              </group>
              <mesh geometry={nodes.Drone_ILens_body_0.geometry} material={nodes.Drone_ILens_body_0.material} />
            </group>
            <group position={[0, -38.68, 20.01]}>
              <group position={[0.01, -5.51, -0.09]} rotation={[0, Math.PI / 2, 0]}>
                <group position={[0, 0, 0]} rotation={[Math.PI / 2, 0.09, -Math.PI / 2]}>
                  <group position={[0, -22.92, 0.03]}>
                    <group rotation={[1.22, 0, -Math.PI]}>
                      <group position={[-0.02, -11.28, 0.08]}>
                        <group position={[0.01, -9.33, -0.08]}>
                          <group position={[0, 0, 0]} rotation={[1.26, 0, 0]}>
                            <mesh geometry={nodes.F_P7_leg_0.geometry} material={nodes.F_P7_leg_0.material} />
                          </group>
                          <mesh geometry={nodes.F_P6_G_leg_0.geometry} material={nodes.F_P6_G_leg_0.material} />
                        </group>
                        <mesh geometry={nodes.F_P5_M_leg_0.geometry} material={nodes.F_P5_M_leg_0.material} />
                      </group>
                      <mesh geometry={nodes.F_P4_leg_0.geometry} material={nodes.F_P4_leg_0.material} />
                    </group>
                    <mesh geometry={nodes.F_P3_G_leg_0.geometry} material={nodes.F_P3_G_leg_0.material} />
                  </group>
                  <mesh geometry={nodes.F_P2_leg_0.geometry} material={nodes.F_P2_leg_0.material} />
                </group>
                <mesh geometry={nodes.F_P1_G_leg_0.geometry} material={nodes.F_P1_G_leg_0.material} />
              </group>
              <mesh geometry={nodes.Drone_leg_F_leg_0.geometry} material={nodes.Drone_leg_F_leg_0.material} />
            </group>
            <mesh geometry={nodes.Drone_Body_body_0.geometry} material={nodes.Drone_Body_body_0.material} />
          </group>
        </group>
        <group position={[0, 143.07, 58.64]} rotation={[0.03, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/drone.glb')
