/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 /Users/ph/Downloads/hydria_apothecary_vase.glb --transform 
Files: /Users/ph/Downloads/hydria_apothecary_vase.glb [18.85MB] > /Users/ph/dev/gltfjsx/hydria_apothecary_vase-transformed.glb [846.31KB] (96%)
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/hydria-apothecary-vase-7d6938c0c0b54b06a0210a982a73023e
Title: Hydria apothecary vase
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hydria_apothecary_vase-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.wire_177028149} position={[-162.834, -228.746, 138.288]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/hydria_apothecary_vase-transformed.glb')
