/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_model" position={[-0.16, 0, -0.22]} rotation={[-Math.PI / 2, 0, -1.47]}>
        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
          <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={nodes.Object_110.material} />
          <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={nodes.Object_112.material} />
          <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={nodes.Object_113.material} />
          <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={nodes.Object_90.material} />
          <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
          <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} />
          <group name="Bota_Espuma_Cabedal_Frente_9" position={[0, 0, -0.06]}>
            <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} />
          </group>
          <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
          <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
          <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
          <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
          <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={nodes.Object_108.material} />
          <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={nodes.Object_93.material} />
          <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={nodes.Object_97.material} />
          <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={nodes.Object_99.material} />
          <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={nodes.Object_101.material} />
          <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={nodes.Object_103.material} />
          <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={nodes.Object_37.material} />
          <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
          <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
          <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={nodes.Object_10.material} />
          <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} />
          <group
            name="Bota_Passador_Ilhos_Grande001_16"
            position={[0.59, 0.64, -0.71]}
            rotation={[-0.67, -0.14, -1.42]}
            scale={[0.98, 0.98, 0.98]}>
            <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} />
            <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
          </group>
          <group
            name="Bota_Passador_Ilhos_Grande002_17"
            position={[-0.49, 0.69, -0.85]}
            rotation={[-0.59, 0.09, 1.36]}
            scale={0.98}>
            <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
            <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={nodes.Object_46.material} />
          </group>
          <group
            name="Bota_Passador_Ilhos_Pequeno001_18"
            position={[0.59, 1.17, -0.84]}
            rotation={[-0.39, 0.02, -1.67]}>
            <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={nodes.Object_48.material} />
            <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
          </group>
          <group
            name="Bota_Passador_Ilhos_Pequeno002_19"
            position={[0.68, 1.56, -0.92]}
            rotation={[-0.39, -0.12, -1.75]}>
            <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
            <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={nodes.Object_52.material} />
          </group>
          <group
            name="Bota_Passador_Ilhos_Pequeno003_20"
            position={[-0.55, 1.61, -1.08]}
            rotation={[-0.43, 0.09, 1.58]}>
            <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={nodes.Object_55.material} />
          </group>
          <group name="Bota_Passador_Ilhos_Pequeno004_21" position={[-0.47, 1.18, -0.98]} rotation={[-0.52, 0, 1.6]}>
            <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={nodes.Object_58.material} />
          </group>
          <group name="Bota_Passador001_22" position={[0.2, 0.25, 0.87]} rotation={[-2.22, -1.18, -2.38]} scale={0.88}>
            <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
            <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={nodes.Object_61.material} />
          </group>
          <group
            name="Bota_Passador002_23"
            position={[0.34, 0.27, 0.66]}
            rotation={[-1.87, -1.13, -2.5]}
            scale={[0.88, 0.88, 0.88]}>
            <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
            <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={nodes.Object_64.material} />
          </group>
          <group name="Bota_Passador003_24" position={[0.44, 0.35, 0.43]} rotation={[-1.86, -0.98, -2.17]} scale={0.88}>
            <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={nodes.Object_67.material} />
          </group>
          <group
            name="Bota_Passador004_25"
            position={[0.54, 0.43, 0.1]}
            rotation={[-1.22, -0.8, -1.66]}
            scale={[0.88, 0.88, 0.88]}>
            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
            <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
          </group>
          <group
            name="Bota_Passador005_26"
            position={[0.56, 0.53, -0.18]}
            rotation={[-1.19, -0.62, -1.62]}
            scale={0.88}>
            <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={nodes.Object_73.material} />
          </group>
          <group name="Bota_Passador006_27" position={[-0.28, 0.27, 0.88]} rotation={[-2.1, 1.25, 2.31]} scale={0.88}>
            <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={nodes.Object_75.material} />
            <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
          </group>
          <group
            name="Bota_Passador007_28"
            position={[-0.34, 0.32, 0.61]}
            rotation={[-1.79, 1.17, 2.35]}
            scale={[0.88, 0.88, 0.88]}>
            <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={nodes.Object_78.material} />
            <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={nodes.Object_79.material} />
          </group>
          <group name="Bota_Passador008_29" position={[-0.41, 0.42, 0.33]} rotation={[-1.31, 1.01, 1.81]} scale={0.88}>
            <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={nodes.Object_81.material} />
            <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
          </group>
          <group
            name="Bota_Passador009_30"
            position={[-0.49, 0.51, 0.01]}
            rotation={[-1.29, 0.76, 1.74]}
            scale={[0.88, 0.88, 0.88]}>
            <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={nodes.Object_84.material} />
            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={nodes.Object_85.material} />
          </group>
          <group name="Bota_Passador010_31" position={[-0.51, 0.61, -0.29]} rotation={[-1.22, 0.58, 1.6]} scale={0.88}>
            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={nodes.Object_87.material} />
            <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
          </group>
          <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={nodes.Object_105.material} />
          <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
          <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
          <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
          <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
          <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={nodes.Object_95.material} />
          <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={nodes.Object_117.material} />
          <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials['Material.002']} />
          <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={nodes.Object_121.material} />
          <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={nodes.Object_119.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoe.glb')
